### ISSUE TITLE
Output percentile indices with (time, lat, lon) order

### ISSUE THREAD

**Issue by ngben** [AusClimateService/indices#7]
Is it possible for percentile indices to be output with time as the left-most dimension? Currently output is (lat, lon, time) which doesn't seem to play nicely with ILAMB. It only occurs for percentile indices, other indices are output with time as the left-most dimension.

**Comment by ngben** [comment]
It seems that compound indices (i.e., CD, CW, WD, WW) are also ordered in (lat, lon, time)

**Comment by DamienIrving** [comment]
No problem - I can set the output as time, lat, lon.

On a related note, at the moment if the input latitude axis is 90 to -90 (as opposed to the more regular -90 to 90) the code will alter the input north and south bounds rather than flip the latitude axis. Would you prefer that all output files have a latitude axis that goes from -90 to 90?

**Comment by DamienIrving** [comment]
I've pushed a new commit to ensure the output is time, lat, lon for all indices: https://github.com/AusClimateService/indices/commit/fcebd4068b7d2442a5a3914e6730ca3b7728ecad

One consequence is that when you specify the index you want at the command line it's case sensitive now (i.e. RX5day instead of rx5day). You can see what all the valid options are by running `python run_icclim.py -h`

**Comment by ngben** [comment]
Thanks Damien, the reversed latitude axis doesn't seem to have caused any issues so far. I'll test the latest commit and hopefully ILAMB will be able to read the indices.
